### ISSUE TITLE
Email or Username Authentication

### ISSUE THREAD

**Issue by plunkettscott** [lavrahq/identity#1]
**Describe the feature.**
Identity should support authentication via email or username with a password.

**Vision for success.**
When prompted with an authentication page, upon entering either a username or email, I should be redirected to a password field to enter a password and continue authenticating.

**Designs**
Shared email or username field which is transitioned to a password field whenever the email or username has been provided. This should happen regardless of whether the email or username is valid in order to protect against automated entries being able to detect whether the email or username entered is a valid account.

**Additional context**
Throttle authentication attempts after so many incorrect attempts
Allow 2FA when 2FA is implemented

**Comment by spjy** [comment]
Looks done to me. I added a throttle middleware for 20 hits per 5 min on /password.
